### PR TITLE
Add DAC support

### LINKED ISSUE #1: stm32f4xx.h: No such file or directory
コンパイルエラーが発生する。

stm32f4xx_hal_def.h:46:23: fatal error: stm32f4xx.h: No such file or directory

```
In file included from ...\ArduinoData\packages\SeeedJP\hardware\SeeedJP_STM32F4\1.0.0\cores\Arduino/STM32CubeF4/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_rcc.h:45:0,

                 from ...\ArduinoData\packages\SeeedJP\hardware\SeeedJP_STM32F4\1.0.0\cores\Arduino/Boards/STM324x9I_EVAL/stm32f4xx_hal_conf.h:243,

                 from ...\ArduinoData\packages\SeeedJP\hardware\SeeedJP_STM32F4\1.0.0\cores\Arduino/STM32CubeF4/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h:46,

                 from ...\Arduino\libraries\Wio_3G_for_Arduino\src\Internal\Wio3GSK6812.cpp:4:

...\ArduinoData\packages\SeeedJP\hardware\SeeedJP_STM32F4\1.0.0\cores\Arduino/STM32CubeF4/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_def.h:46:23: fatal error: stm32f4xx.h: No such file or directory
```

### PR DESCRIPTION
**Pull request by kekyo**
* DAC manipulator implementation with standard arduino interface (analogWrite function).
* Tested arduino IDE code: https://gist.github.com/kekyo/337c38076ce52878bf45e73ebc0af4ad
* Sorry, this branch contains your dev commit at "Fix #1" f0c88e732a085e065380586edf2f2e8d84e62a3b and branched to topic "dac."

### CODE REVIEW

**Comment by kekyo** [comment]
Analyzer captured:

image

**Comment by matsujirushi** [comment]
何故、CMSIS配下がドサッと変更になっているのでしょう？
`cores/Arduino/STM32CubeF4/Drivers/CMSIS/Device/ST/STM32F4xx/Include`

**Comment by matsujirushi** [comment]
Please remove dev-commit and re-post pull request.
Thanks.

**Comment by kekyo** [comment]
Move to https://github.com/SeeedJP/SeeedJP_STM32F4/pull/3

**Pull request closed without merging**
